#!/bin/bash

root=/home/cvetan/git/GenMining

cd ${root}

java -cp target/GenMining-0.0.1-SNAPSHOT-jar-with-dependencies.jar app.RunMe

java -cp target/GenMining-0.0.1-SNAPSHOT-jar-with-dependencies.jar app.multidata.RunMD

